### ISSUE TITLE
Discrepancy in the operation of failureSeverities?

### ISSUE THREAD

**Issue by jatinmehrotra** [Checkmarx/kics-cdk-validator-plugin#21]
## What 

I am trying to test the `failureSeverities`. According to [README ](https://github.com/Checkmarx/kics-cdk-validator-plugin/blob/main/README.md)

> The other option is to provide failureSeverities if you still want to show the query in the results, but you don't want it to fail the execution. By default this is set to [Severity.HIGH, Severity.MEDIUM].

- As per above understanding failureSeverities property will not fail the execution on HIGH and MEDIUM category severities as they are default in other words it will fail deployment on LOW severities. 
- This also means if I pass LOW as key it should pass the deployment.

## Expected Behavior 

- I wanted to deploy and only see the report, going by the readme since high and medium are default, I tried to pass the LOW in order to pass the deployment

```
import { Duration, Stack, StackProps } from 'aws-cdk-lib';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as subs from 'aws-cdk-lib/aws-sns-subscriptions';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as s3 from 'aws-cdk-lib/aws-s3';
import { Construct } from 'constructs';


export class CdkLeftShiftStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    new s3.Bucket(this, 'MyFirstBucket');

    const queue = new sqs.Queue(this, 'CdkLeftShiftQueue', {
      visibilityTimeout: Duration.seconds(300)
    });

    const topic = new sns.Topic(this, 'CdkLeftShiftTopic');

    topic.addSubscription(new subs.SqsSubscription(queue));
  }
}


```

```
const app = new cdk.App({
    policyValidationBeta1: [new KicsValidator({
        failureSeverities: [Severity.HIGH,Severity.MEDIUM,Severity.LOW],
    })],
});
```

- Even If I explicitly pass this it still fails the deployment. 

- Is the above behaviour intended?

### Actual behaviour 

- No matter what value I pass deployment fails which contradicts README

### PLUGIN.ts comments means the OPPOSITE

> * List of severities which should cause the
>    * execution to fail
> 

- However the [plugin.ts](https://github.com/Checkmarx/kics-cdk-validator-plugin/blob/eac526525bc8397eedb7f55b18edc5e1604a2fe7/src/plugin.ts#L45) comments says the completely opposite which makes sense as per above comments and behaviour.

## Additional context

- IMO there is typo of `dont`.  It should be `The other option is to provide failureSeverities if you still want to show the query in the results, but you want it to fail the execution. By default this is set to [Severity.HIGH, Severity.MEDIUM].`

- I tried to verify the above where I want to pass the deployment 

```
const app = new cdk.App({
    policyValidationBeta1: [new KicsValidator({
        failureSeverities: [],
    })],
});


```

- As expected deployment pass but this is 50 % correct as I was expecting it to show the findings in the report which it didnt and reported as `success`. Again is this too intended?

**Comment by jatinmehrotra** [comment]
@cxMiguelSilva @gabriel-cx 

Is the above intended?

**Comment by cx-miguel-dasilva** [comment]
Hi @jatinmehrotra, 
Yes, I agree with you, the flag description is confusing. The following mapping represents how the flags are linked with the engine flags:
| CDK Kics Validator Plugin | KICS engine |
|---|---|
| failureSeverities | --fail-on |
| excludeSeverities | --exclude-severities |

engine docs: [docs.kics.io](https://docs.kics.io/latest/commands/) 
We will update the readme to better explain the fail-on/failureSeverities behavior

Regarding the `Additional context`, we will need to investigate and see that the report is shown even if is deemed as passed.

**Comment by jatinmehrotra** [comment]
@cxMiguelSilva 

Thank you for you acknowledging.

I would have send the PR for fix( since I understand how build works 😄 ) but  the additional context behaviour is unclear to me so I will wait for your results

**Comment by cx-miguel-dasilva** [comment]
Hi @jatinmehrotra, hope you are doing great!
Firstly, I want to apologize for the late response to this topic.
Regarding the doubt present in the additional context, I was able to see how the evaluation is done, and what is passed to the aws cdk. All that logic takes place [here ](https://github.com/Checkmarx/kics-cdk-validator-plugin/blob/main/src/plugin.ts#L106-L134). The return parameters are defined by the interface available on the aws cdk [(docs here)](https://docs.aws.amazon.com/cdk/api/v2/python/aws_cdk/PolicyValidationPluginReportBeta1.html). 

Concluding, to present the violations, even though they are not specified as failure ones, there will need to be a specific logic implemented on the aws cdk side. Let me know what you think.
